// GENERATED by oracle/oracle.py — an independent Fraction-based calculator. Do not edit by hand.
// Every case is one random piece priced with GST 1.5% + 1.5% (intra-state) or 3% (inter-state).
export interface OracleCase {
  gross: number; stone: number; purity: string; fineness: number; quotedFineness: number; rate: number; pieces: number; stoneValue: number; intra: boolean; cost?: number;
  making?: { type: "PERCENTAGE" | "PER_GRAM" | "FIXED" | "PER_PIECE"; value: number };
  wastage?: { type: "PERCENTAGE" | "FIXED_WEIGHT"; value: number } | { type: "NONE" };
  discount?: { type: "PERCENTAGE" | "FLAT"; value: number; appliesTo: "TOTAL" | "MAKING_CHARGES" };
  expected: { net: number; fine: number; metalValue: number; wastageWeight: number; wastageValue: number; makingCharges: number; subtotal: number; discount: number; taxableValue: number; cgst: number; sgst: number; igst: number; totalTax: number; finalAmount: number; grossMargin?: number; marginPercentage?: number | null };
}

export const ORACLE_CASES: OracleCase[] = [
  {
    "gross": 33.982,
    "stone": 0.0,
    "purity": "925",
    "fineness": 0.925,
    "quotedFineness": 0.999,
    "rate": 368470,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "FIXED",
      "value": 267888
    },
    "expected": {
      "net": 33.982,
      "fine": 31.433,
      "metalValue": 11593840,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 267888,
      "subtotal": 11861728,
      "discount": 0,
      "taxableValue": 11861728,
      "cgst": 177926,
      "sgst": 177926,
      "igst": 0,
      "totalTax": 355852,
      "finalAmount": 12217580
    }
  },
  {
    "gross": 18.492,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.585,
    "rate": 455240,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 10.583
    },
    "expected": {
      "net": 18.492,
      "fine": 10.818,
      "metalValue": 8418298,
      "wastageWeight": 10.583,
      "wastageValue": 4817805,
      "makingCharges": 0,
      "subtotal": 13236103,
      "discount": 0,
      "taxableValue": 13236103,
      "cgst": 0,
      "sgst": 0,
      "igst": 397083,
      "totalTax": 397083,
      "finalAmount": 13633186
    }
  },
  {
    "gross": 122.872,
    "stone": 29.929,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 444141,
    "pieces": 5,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 295652
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 13.8
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 48.22,
      "appliesTo": "TOTAL"
    },
    "cost": 16561259,
    "expected": {
      "net": 92.943,
      "fine": 54.372,
      "metalValue": 24172854,
      "wastageWeight": 12.826,
      "wastageValue": 3335819,
      "makingCharges": 1478260,
      "subtotal": 28986933,
      "discount": 13977499,
      "taxableValue": 15009434,
      "cgst": 225142,
      "sgst": 225142,
      "igst": 0,
      "totalTax": 450284,
      "finalAmount": 15459718,
      "grossMargin": -1551825,
      "marginPercentage": -10.34
    }
  },
  {
    "gross": 173.04,
    "stone": 0.0,
    "purity": "24K",
    "fineness": 0.999,
    "quotedFineness": 0.999,
    "rate": 42423,
    "pieces": 12,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "FIXED",
      "value": 228168
    },
    "cost": 7437679,
    "expected": {
      "net": 173.04,
      "fine": 172.867,
      "metalValue": 7340876,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 228168,
      "subtotal": 7569044,
      "discount": 0,
      "taxableValue": 7569044,
      "cgst": 113536,
      "sgst": 113536,
      "igst": 0,
      "totalTax": 227072,
      "finalAmount": 7796116,
      "grossMargin": 131365,
      "marginPercentage": 1.74
    }
  },
  {
    "gross": 77.241,
    "stone": 0.0,
    "purity": "925",
    "fineness": 0.925,
    "quotedFineness": 0.999,
    "rate": 502446,
    "pieces": 12,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PERCENTAGE",
      "value": 6.92
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 49.47,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 36940674,
    "expected": {
      "net": 77.241,
      "fine": 71.448,
      "metalValue": 35934659,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 2486678,
      "subtotal": 38421337,
      "discount": 1230160,
      "taxableValue": 37191177,
      "cgst": 0,
      "sgst": 0,
      "igst": 1115735,
      "totalTax": 1115735,
      "finalAmount": 38306912,
      "grossMargin": 250503,
      "marginPercentage": 0.67
    }
  },
  {
    "gross": 207.148,
    "stone": 0.0,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.95,
    "rate": 845734,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 494602
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 10.66
    },
    "expected": {
      "net": 207.148,
      "fine": 196.791,
      "metalValue": 175192107,
      "wastageWeight": 22.082,
      "wastageValue": 18675498,
      "makingCharges": 494602,
      "subtotal": 194362207,
      "discount": 0,
      "taxableValue": 194362207,
      "cgst": 2915433,
      "sgst": 2915433,
      "igst": 0,
      "totalTax": 5830866,
      "finalAmount": 200193073
    }
  },
  {
    "gross": 38.153,
    "stone": 0.0,
    "purity": "22K",
    "fineness": 0.916,
    "quotedFineness": 0.999,
    "rate": 870798,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 86225
    },
    "cost": 1790014,
    "expected": {
      "net": 38.153,
      "fine": 34.948,
      "metalValue": 30463241,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 3289742,
      "subtotal": 33752983,
      "discount": 0,
      "taxableValue": 33752983,
      "cgst": 0,
      "sgst": 0,
      "igst": 1012589,
      "totalTax": 1012589,
      "finalAmount": 34765572,
      "grossMargin": 31962969,
      "marginPercentage": 94.7
    }
  },
  {
    "gross": 245.809,
    "stone": 14.912,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.999,
    "rate": 86156,
    "pieces": 12,
    "stoneValue": 3131285,
    "intra": true,
    "making": {
      "type": "PERCENTAGE",
      "value": 22.32
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 12.5
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 63.83,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 49863951,
    "expected": {
      "net": 230.897,
      "fine": 219.352,
      "metalValue": 18917421,
      "wastageWeight": 28.862,
      "wastageValue": 2364667,
      "makingCharges": 4222368,
      "subtotal": 28635741,
      "discount": 2695137,
      "taxableValue": 25940604,
      "cgst": 389109,
      "sgst": 389109,
      "igst": 0,
      "totalTax": 778218,
      "finalAmount": 26718822,
      "grossMargin": -23923347,
      "marginPercentage": -92.22
    }
  },
  {
    "gross": 161.806,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 793458,
    "pieces": 5,
    "stoneValue": 0,
    "intra": false,
    "wastage": {
      "type": "PERCENTAGE",
      "value": 14.35
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 31.72,
      "appliesTo": "MAKING_CHARGES"
    },
    "expected": {
      "net": 161.806,
      "fine": 121.355,
      "metalValue": 128386265,
      "wastageWeight": 23.219,
      "wastageValue": 18423301,
      "makingCharges": 0,
      "subtotal": 146809566,
      "discount": 0,
      "taxableValue": 146809566,
      "cgst": 0,
      "sgst": 0,
      "igst": 4404287,
      "totalTax": 4404287,
      "finalAmount": 151213853
    }
  },
  {
    "gross": 179.99,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.585,
    "rate": 662258,
    "pieces": 5,
    "stoneValue": 0,
    "intra": false,
    "wastage": {
      "type": "PERCENTAGE",
      "value": 0.78
    },
    "discount": {
      "type": "FLAT",
      "value": 87871391,
      "appliesTo": "TOTAL"
    },
    "cost": 166457426,
    "expected": {
      "net": 179.99,
      "fine": 105.294,
      "metalValue": 119199817,
      "wastageWeight": 1.404,
      "wastageValue": 929810,
      "makingCharges": 0,
      "subtotal": 120129627,
      "discount": 87871391,
      "taxableValue": 32258236,
      "cgst": 0,
      "sgst": 0,
      "igst": 967747,
      "totalTax": 967747,
      "finalAmount": 33225983,
      "grossMargin": -134199190,
      "marginPercentage": -416.02
    }
  },
  {
    "gross": 66.515,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 898085,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 56.42
    },
    "cost": 188136725,
    "expected": {
      "net": 66.515,
      "fine": 49.886,
      "metalValue": 59736124,
      "wastageWeight": 56.42,
      "wastageValue": 50669956,
      "makingCharges": 0,
      "subtotal": 110406080,
      "discount": 0,
      "taxableValue": 110406080,
      "cgst": 0,
      "sgst": 0,
      "igst": 3312182,
      "totalTax": 3312182,
      "finalAmount": 113718262,
      "grossMargin": -77730645,
      "marginPercentage": -70.4
    }
  },
  {
    "gross": 92.466,
    "stone": 47.31,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 364871,
    "pieces": 2,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "FIXED",
      "value": 348271
    },
    "wastage": {
      "type": "NONE"
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 90.0,
      "appliesTo": "MAKING_CHARGES"
    },
    "expected": {
      "net": 45.156,
      "fine": 26.416,
      "metalValue": 9648175,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 348271,
      "subtotal": 9996446,
      "discount": 313444,
      "taxableValue": 9683002,
      "cgst": 0,
      "sgst": 0,
      "igst": 290490,
      "totalTax": 290490,
      "finalAmount": 9973492
    }
  },
  {
    "gross": 115.213,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.585,
    "rate": 323095,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 305485
    },
    "wastage": {
      "type": "NONE"
    },
    "expected": {
      "net": 115.213,
      "fine": 67.4,
      "metalValue": 37224744,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 305485,
      "subtotal": 37530229,
      "discount": 0,
      "taxableValue": 37530229,
      "cgst": 0,
      "sgst": 0,
      "igst": 1125907,
      "totalTax": 1125907,
      "finalAmount": 38656136
    }
  },
  {
    "gross": 189.284,
    "stone": 0.0,
    "purity": "22K",
    "fineness": 0.916,
    "quotedFineness": 0.999,
    "rate": 362640,
    "pieces": 1,
    "stoneValue": 852214,
    "intra": true,
    "discount": {
      "type": "PERCENTAGE",
      "value": 80.16,
      "appliesTo": "TOTAL"
    },
    "expected": {
      "net": 189.284,
      "fine": 173.384,
      "metalValue": 62938965,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 0,
      "subtotal": 63791179,
      "discount": 51135009,
      "taxableValue": 12656170,
      "cgst": 189843,
      "sgst": 189843,
      "igst": 0,
      "totalTax": 379686,
      "finalAmount": 13035856
    }
  },
  {
    "gross": 124.051,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 447425,
    "pieces": 2,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 95198
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 9.87
    },
    "discount": {
      "type": "FLAT",
      "value": 24375786,
      "appliesTo": "TOTAL"
    },
    "expected": {
      "net": 124.051,
      "fine": 93.038,
      "metalValue": 41669308,
      "wastageWeight": 12.244,
      "wastageValue": 4112817,
      "makingCharges": 190396,
      "subtotal": 45972521,
      "discount": 24375786,
      "taxableValue": 21596735,
      "cgst": 0,
      "sgst": 0,
      "igst": 647902,
      "totalTax": 647902,
      "finalAmount": 22244637
    }
  },
  {
    "gross": 20.052,
    "stone": 0.0,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.999,
    "rate": 484236,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PERCENTAGE",
      "value": 23.06
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 2.224
    },
    "discount": {
      "type": "FLAT",
      "value": 2269670,
      "appliesTo": "TOTAL"
    },
    "expected": {
      "net": 20.052,
      "fine": 19.049,
      "metalValue": 9233639,
      "wastageWeight": 2.224,
      "wastageValue": 1024118,
      "makingCharges": 2129277,
      "subtotal": 12387034,
      "discount": 2269670,
      "taxableValue": 10117364,
      "cgst": 0,
      "sgst": 0,
      "igst": 303521,
      "totalTax": 303521,
      "finalAmount": 10420885
    }
  },
  {
    "gross": 87.737,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 687138,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 414162
    },
    "wastage": {
      "type": "NONE"
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 32.21,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 74758040,
    "expected": {
      "net": 87.737,
      "fine": 65.803,
      "metalValue": 60287427,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 414162,
      "subtotal": 60701589,
      "discount": 133402,
      "taxableValue": 60568187,
      "cgst": 908523,
      "sgst": 908523,
      "igst": 0,
      "totalTax": 1817046,
      "finalAmount": 62385233,
      "grossMargin": -14189853,
      "marginPercentage": -23.43
    }
  },
  {
    "gross": 167.013,
    "stone": 0.0,
    "purity": "24K",
    "fineness": 0.999,
    "quotedFineness": 0.999,
    "rate": 738199,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PERCENTAGE",
      "value": 11.0
    },
    "wastage": {
      "type": "NONE"
    },
    "cost": 146265057,
    "expected": {
      "net": 167.013,
      "fine": 166.846,
      "metalValue": 123288830,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 13561771,
      "subtotal": 136850601,
      "discount": 0,
      "taxableValue": 136850601,
      "cgst": 2052759,
      "sgst": 2052759,
      "igst": 0,
      "totalTax": 4105518,
      "finalAmount": 140956119,
      "grossMargin": -9414456,
      "marginPercentage": -6.88
    }
  },
  {
    "gross": 242.68,
    "stone": 0.0,
    "purity": "925",
    "fineness": 0.925,
    "quotedFineness": 0.925,
    "rate": 293412,
    "pieces": 1,
    "stoneValue": 3441107,
    "intra": true,
    "making": {
      "type": "PERCENTAGE",
      "value": 1.99
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 10.26
    },
    "cost": 151598392,
    "expected": {
      "net": 242.68,
      "fine": 224.479,
      "metalValue": 71205224,
      "wastageWeight": 24.899,
      "wastageValue": 7305665,
      "makingCharges": 1416984,
      "subtotal": 83368980,
      "discount": 0,
      "taxableValue": 83368980,
      "cgst": 1250535,
      "sgst": 1250535,
      "igst": 0,
      "totalTax": 2501070,
      "finalAmount": 85870050,
      "grossMargin": -68229412,
      "marginPercentage": -81.84
    }
  },
  {
    "gross": 239.677,
    "stone": 134.01,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 30823,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "discount": {
      "type": "PERCENTAGE",
      "value": 72.34,
      "appliesTo": "MAKING_CHARGES"
    },
    "expected": {
      "net": 105.667,
      "fine": 61.815,
      "metalValue": 1907237,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 0,
      "subtotal": 1907237,
      "discount": 0,
      "taxableValue": 1907237,
      "cgst": 0,
      "sgst": 0,
      "igst": 57217,
      "totalTax": 57217,
      "finalAmount": 1964454
    }
  },
  {
    "gross": 178.987,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 147882,
    "pieces": 2,
    "stoneValue": 47698,
    "intra": false,
    "making": {
      "type": "FIXED",
      "value": 56348
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 13.67
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 64.63,
      "appliesTo": "TOTAL"
    },
    "expected": {
      "net": 178.987,
      "fine": 134.24,
      "metalValue": 26468956,
      "wastageWeight": 24.468,
      "wastageValue": 3618377,
      "makingCharges": 56348,
      "subtotal": 30191379,
      "discount": 19512688,
      "taxableValue": 10678691,
      "cgst": 0,
      "sgst": 0,
      "igst": 320361,
      "totalTax": 320361,
      "finalAmount": 10999052
    }
  },
  {
    "gross": 86.781,
    "stone": 0.0,
    "purity": "24K",
    "fineness": 0.999,
    "quotedFineness": 0.999,
    "rate": 152803,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PERCENTAGE",
      "value": 14.44
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 43.475
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 35.46,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 4147209,
    "expected": {
      "net": 86.781,
      "fine": 86.694,
      "metalValue": 13260397,
      "wastageWeight": 43.475,
      "wastageValue": 6643110,
      "makingCharges": 1914801,
      "subtotal": 21818308,
      "discount": 678988,
      "taxableValue": 21139320,
      "cgst": 317090,
      "sgst": 317090,
      "igst": 0,
      "totalTax": 634180,
      "finalAmount": 21773500,
      "grossMargin": 16992111,
      "marginPercentage": 80.38
    }
  },
  {
    "gross": 147.498,
    "stone": 51.866,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.95,
    "rate": 474416,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 144216
    },
    "cost": 46621272,
    "expected": {
      "net": 95.632,
      "fine": 90.85,
      "metalValue": 45369351,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 144216,
      "subtotal": 45513567,
      "discount": 0,
      "taxableValue": 45513567,
      "cgst": 682704,
      "sgst": 682704,
      "igst": 0,
      "totalTax": 1365408,
      "finalAmount": 46878975,
      "grossMargin": -1107705,
      "marginPercentage": -2.43
    }
  },
  {
    "gross": 75.443,
    "stone": 0.0,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.95,
    "rate": 124711,
    "pieces": 12,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 463317
    },
    "wastage": {
      "type": "NONE"
    },
    "expected": {
      "net": 75.443,
      "fine": 71.671,
      "metalValue": 9408572,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 5559804,
      "subtotal": 14968376,
      "discount": 0,
      "taxableValue": 14968376,
      "cgst": 0,
      "sgst": 0,
      "igst": 449051,
      "totalTax": 449051,
      "finalAmount": 15417427
    }
  },
  {
    "gross": 114.863,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 173818,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_GRAM",
      "value": 82437
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 43.574
    },
    "cost": 9764075,
    "expected": {
      "net": 114.863,
      "fine": 86.147,
      "metalValue": 19965257,
      "wastageWeight": 43.574,
      "wastageValue": 7573946,
      "makingCharges": 9468961,
      "subtotal": 37008164,
      "discount": 0,
      "taxableValue": 37008164,
      "cgst": 555122,
      "sgst": 555122,
      "igst": 0,
      "totalTax": 1110244,
      "finalAmount": 38118408,
      "grossMargin": 27244089,
      "marginPercentage": 73.62
    }
  },
  {
    "gross": 94.399,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.585,
    "rate": 242131,
    "pieces": 1,
    "stoneValue": 2412943,
    "intra": true,
    "making": {
      "type": "PER_GRAM",
      "value": 36187
    },
    "wastage": {
      "type": "NONE"
    },
    "cost": 26760518,
    "expected": {
      "net": 94.399,
      "fine": 55.223,
      "metalValue": 22856924,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 3416017,
      "subtotal": 28685884,
      "discount": 0,
      "taxableValue": 28685884,
      "cgst": 430288,
      "sgst": 430288,
      "igst": 0,
      "totalTax": 860576,
      "finalAmount": 29546460,
      "grossMargin": 1925366,
      "marginPercentage": 6.71
    }
  },
  {
    "gross": 54.511,
    "stone": 25.069,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 603976,
    "pieces": 5,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 419505
    },
    "cost": 2301105,
    "expected": {
      "net": 29.442,
      "fine": 17.224,
      "metalValue": 10413036,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 2097525,
      "subtotal": 12510561,
      "discount": 0,
      "taxableValue": 12510561,
      "cgst": 0,
      "sgst": 0,
      "igst": 375317,
      "totalTax": 375317,
      "finalAmount": 12885878,
      "grossMargin": 10209456,
      "marginPercentage": 81.61
    }
  },
  {
    "gross": 147.159,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 265852,
    "pieces": 5,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 153787
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 80.99
    },
    "cost": 82752418,
    "expected": {
      "net": 147.159,
      "fine": 110.369,
      "metalValue": 39122514,
      "wastageWeight": 80.99,
      "wastageValue": 21531353,
      "makingCharges": 768935,
      "subtotal": 61422802,
      "discount": 0,
      "taxableValue": 61422802,
      "cgst": 921342,
      "sgst": 921342,
      "igst": 0,
      "totalTax": 1842684,
      "finalAmount": 63265486,
      "grossMargin": -21329616,
      "marginPercentage": -34.73
    }
  },
  {
    "gross": 76.137,
    "stone": 53.627,
    "purity": "22K",
    "fineness": 0.916,
    "quotedFineness": 0.916,
    "rate": 140524,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 166221
    },
    "wastage": {
      "type": "NONE"
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 38.0,
      "appliesTo": "TOTAL"
    },
    "expected": {
      "net": 22.51,
      "fine": 20.619,
      "metalValue": 3163195,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 3741635,
      "subtotal": 6904830,
      "discount": 2623835,
      "taxableValue": 4280995,
      "cgst": 0,
      "sgst": 0,
      "igst": 128430,
      "totalTax": 128430,
      "finalAmount": 4409425
    }
  },
  {
    "gross": 97.104,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 899049,
    "pieces": 12,
    "stoneValue": 0,
    "intra": true,
    "discount": {
      "type": "PERCENTAGE",
      "value": 18.27,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 120540898,
    "expected": {
      "net": 97.104,
      "fine": 72.828,
      "metalValue": 65541482,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 0,
      "subtotal": 65541482,
      "discount": 0,
      "taxableValue": 65541482,
      "cgst": 983122,
      "sgst": 983122,
      "igst": 0,
      "totalTax": 1966244,
      "finalAmount": 67507726,
      "grossMargin": -54999416,
      "marginPercentage": -83.92
    }
  },
  {
    "gross": 71.939,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.585,
    "rate": 328855,
    "pieces": 12,
    "stoneValue": 3415748,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 130697
    },
    "cost": 34715961,
    "expected": {
      "net": 71.939,
      "fine": 42.084,
      "metalValue": 23657500,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 9402211,
      "subtotal": 36475459,
      "discount": 0,
      "taxableValue": 36475459,
      "cgst": 0,
      "sgst": 0,
      "igst": 1094264,
      "totalTax": 1094264,
      "finalAmount": 37569723,
      "grossMargin": 1759498,
      "marginPercentage": 4.82
    }
  },
  {
    "gross": 26.032,
    "stone": 0.0,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.95,
    "rate": 189892,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_GRAM",
      "value": 162843
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 1.133
    },
    "expected": {
      "net": 26.032,
      "fine": 24.73,
      "metalValue": 4943269,
      "wastageWeight": 1.133,
      "wastageValue": 215148,
      "makingCharges": 4239129,
      "subtotal": 9397546,
      "discount": 0,
      "taxableValue": 9397546,
      "cgst": 140963,
      "sgst": 140963,
      "igst": 0,
      "totalTax": 281926,
      "finalAmount": 9679472
    }
  },
  {
    "gross": 57.309,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 540714,
    "pieces": 5,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "FIXED",
      "value": 136567
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 6.79
    },
    "cost": 8690036,
    "expected": {
      "net": 57.309,
      "fine": 42.982,
      "metalValue": 23264098,
      "wastageWeight": 3.891,
      "wastageValue": 1579518,
      "makingCharges": 136567,
      "subtotal": 24980183,
      "discount": 0,
      "taxableValue": 24980183,
      "cgst": 374703,
      "sgst": 374703,
      "igst": 0,
      "totalTax": 749406,
      "finalAmount": 25729589,
      "grossMargin": 16290147,
      "marginPercentage": 65.21
    }
  },
  {
    "gross": 77.321,
    "stone": 0.0,
    "purity": "22K",
    "fineness": 0.916,
    "quotedFineness": 0.999,
    "rate": 760718,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "discount": {
      "type": "FLAT",
      "value": 16050289,
      "appliesTo": "TOTAL"
    },
    "cost": 87838870,
    "expected": {
      "net": 77.321,
      "fine": 70.826,
      "metalValue": 53932573,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 0,
      "subtotal": 53932573,
      "discount": 16050289,
      "taxableValue": 37882284,
      "cgst": 0,
      "sgst": 0,
      "igst": 1136469,
      "totalTax": 1136469,
      "finalAmount": 39018753,
      "grossMargin": -49956586,
      "marginPercentage": -131.87
    }
  },
  {
    "gross": 115.043,
    "stone": 94.438,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.999,
    "rate": 866186,
    "pieces": 12,
    "stoneValue": 3457007,
    "intra": true,
    "making": {
      "type": "PERCENTAGE",
      "value": 17.91
    },
    "cost": 8486681,
    "expected": {
      "net": 20.605,
      "fine": 19.575,
      "metalValue": 16972347,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 3039747,
      "subtotal": 23469101,
      "discount": 0,
      "taxableValue": 23469101,
      "cgst": 352037,
      "sgst": 352037,
      "igst": 0,
      "totalTax": 704074,
      "finalAmount": 24173175,
      "grossMargin": 14982420,
      "marginPercentage": 63.84
    }
  },
  {
    "gross": 75.31,
    "stone": 0.0,
    "purity": "24K",
    "fineness": 0.999,
    "quotedFineness": 0.999,
    "rate": 75059,
    "pieces": 2,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_GRAM",
      "value": 196732
    },
    "wastage": {
      "type": "NONE"
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 11.86,
      "appliesTo": "TOTAL"
    },
    "cost": 26196305,
    "expected": {
      "net": 75.31,
      "fine": 75.235,
      "metalValue": 5652693,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 14815887,
      "subtotal": 20468580,
      "discount": 2427574,
      "taxableValue": 18041006,
      "cgst": 270615,
      "sgst": 270615,
      "igst": 0,
      "totalTax": 541230,
      "finalAmount": 18582236,
      "grossMargin": -8155299,
      "marginPercentage": -45.2
    }
  },
  {
    "gross": 247.748,
    "stone": 0.0,
    "purity": "22K",
    "fineness": 0.916,
    "quotedFineness": 0.999,
    "rate": 500981,
    "pieces": 5,
    "stoneValue": 471535,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 184811
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 0.91
    },
    "cost": 66784856,
    "expected": {
      "net": 247.748,
      "fine": 226.937,
      "metalValue": 113805014,
      "wastageWeight": 2.255,
      "wastageValue": 1035852,
      "makingCharges": 45786556,
      "subtotal": 161098957,
      "discount": 0,
      "taxableValue": 161098957,
      "cgst": 0,
      "sgst": 0,
      "igst": 4832969,
      "totalTax": 4832969,
      "finalAmount": 165931926,
      "grossMargin": 94314101,
      "marginPercentage": 58.54
    }
  },
  {
    "gross": 137.263,
    "stone": 0.0,
    "purity": "24K",
    "fineness": 0.999,
    "quotedFineness": 0.999,
    "rate": 249439,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_GRAM",
      "value": 195988
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 54.411
    },
    "discount": {
      "type": "FLAT",
      "value": 12045300,
      "appliesTo": "MAKING_CHARGES"
    },
    "expected": {
      "net": 137.263,
      "fine": 137.126,
      "metalValue": 34238745,
      "wastageWeight": 54.411,
      "wastageValue": 13572225,
      "makingCharges": 26901901,
      "subtotal": 74712871,
      "discount": 12045300,
      "taxableValue": 62667571,
      "cgst": 940014,
      "sgst": 940014,
      "igst": 0,
      "totalTax": 1880028,
      "finalAmount": 64547599
    }
  },
  {
    "gross": 82.163,
    "stone": 37.696,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.95,
    "rate": 679209,
    "pieces": 1,
    "stoneValue": 536372,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 364749
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 56.09,
      "appliesTo": "TOTAL"
    },
    "cost": 44447664,
    "expected": {
      "net": 44.467,
      "fine": 42.244,
      "metalValue": 30202387,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 364749,
      "subtotal": 31103508,
      "discount": 17445958,
      "taxableValue": 13657550,
      "cgst": 204863,
      "sgst": 204863,
      "igst": 0,
      "totalTax": 409726,
      "finalAmount": 14067276,
      "grossMargin": -30790114,
      "marginPercentage": -225.44
    }
  },
  {
    "gross": 47.901,
    "stone": 13.289,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.95,
    "rate": 863627,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "discount": {
      "type": "PERCENTAGE",
      "value": 17.44,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 17840289,
    "expected": {
      "net": 34.612,
      "fine": 32.881,
      "metalValue": 29891858,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 0,
      "subtotal": 29891858,
      "discount": 0,
      "taxableValue": 29891858,
      "cgst": 0,
      "sgst": 0,
      "igst": 896756,
      "totalTax": 896756,
      "finalAmount": 30788614,
      "grossMargin": 12051569,
      "marginPercentage": 40.32
    }
  },
  {
    "gross": 176.563,
    "stone": 5.261,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 79759,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "FIXED",
      "value": 245120
    },
    "wastage": {
      "type": "NONE"
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 12.31,
      "appliesTo": "MAKING_CHARGES"
    },
    "expected": {
      "net": 171.302,
      "fine": 128.477,
      "metalValue": 10257415,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 245120,
      "subtotal": 10502535,
      "discount": 30174,
      "taxableValue": 10472361,
      "cgst": 0,
      "sgst": 0,
      "igst": 314171,
      "totalTax": 314171,
      "finalAmount": 10786532
    }
  },
  {
    "gross": 154.729,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 186397,
    "pieces": 2,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 212150
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 70.0,
      "appliesTo": "TOTAL"
    },
    "cost": 2597612,
    "expected": {
      "net": 154.729,
      "fine": 90.516,
      "metalValue": 16888886,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 424300,
      "subtotal": 17313186,
      "discount": 12119230,
      "taxableValue": 5193956,
      "cgst": 0,
      "sgst": 0,
      "igst": 155819,
      "totalTax": 155819,
      "finalAmount": 5349775,
      "grossMargin": 2596344,
      "marginPercentage": 49.99
    }
  },
  {
    "gross": 117.567,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 217446,
    "pieces": 2,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "FIXED",
      "value": 222588
    },
    "discount": {
      "type": "FLAT",
      "value": 18375970,
      "appliesTo": "TOTAL"
    },
    "expected": {
      "net": 117.567,
      "fine": 88.175,
      "metalValue": 19192548,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 222588,
      "subtotal": 19415136,
      "discount": 18375970,
      "taxableValue": 1039166,
      "cgst": 15587,
      "sgst": 15587,
      "igst": 0,
      "totalTax": 31174,
      "finalAmount": 1070340
    }
  },
  {
    "gross": 12.367,
    "stone": 4.594,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 668605,
    "pieces": 12,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 184055
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 1.83
    },
    "expected": {
      "net": 7.773,
      "fine": 4.547,
      "metalValue": 3043327,
      "wastageWeight": 1.83,
      "wastageValue": 716492,
      "makingCharges": 2208660,
      "subtotal": 5968479,
      "discount": 0,
      "taxableValue": 5968479,
      "cgst": 0,
      "sgst": 0,
      "igst": 179054,
      "totalTax": 179054,
      "finalAmount": 6147533
    }
  },
  {
    "gross": 225.773,
    "stone": 194.078,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 203452,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_GRAM",
      "value": 72368
    },
    "cost": 14600063,
    "expected": {
      "net": 31.695,
      "fine": 23.771,
      "metalValue": 6448411,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 2293704,
      "subtotal": 8742115,
      "discount": 0,
      "taxableValue": 8742115,
      "cgst": 131132,
      "sgst": 131132,
      "igst": 0,
      "totalTax": 262264,
      "finalAmount": 9004379,
      "grossMargin": -5857948,
      "marginPercentage": -67.01
    }
  },
  {
    "gross": 151.248,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.75,
    "rate": 645472,
    "pieces": 2,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "FIXED",
      "value": 222864
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 20.3,
      "appliesTo": "TOTAL"
    },
    "cost": 80081724,
    "expected": {
      "net": 151.248,
      "fine": 113.436,
      "metalValue": 97626349,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 222864,
      "subtotal": 97849213,
      "discount": 19863390,
      "taxableValue": 77985823,
      "cgst": 0,
      "sgst": 0,
      "igst": 2339575,
      "totalTax": 2339575,
      "finalAmount": 80325398,
      "grossMargin": -2095901,
      "marginPercentage": -2.69
    }
  },
  {
    "gross": 84.911,
    "stone": 0.0,
    "purity": "925",
    "fineness": 0.925,
    "quotedFineness": 0.925,
    "rate": 136722,
    "pieces": 5,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 135019
    },
    "discount": {
      "type": "FLAT",
      "value": 12461730,
      "appliesTo": "TOTAL"
    },
    "cost": 17720896,
    "expected": {
      "net": 84.911,
      "fine": 78.543,
      "metalValue": 11609202,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 11464598,
      "subtotal": 23073800,
      "discount": 12461730,
      "taxableValue": 10612070,
      "cgst": 0,
      "sgst": 0,
      "igst": 318362,
      "totalTax": 318362,
      "finalAmount": 10930432,
      "grossMargin": -7108826,
      "marginPercentage": -66.99
    }
  },
  {
    "gross": 23.189,
    "stone": 0.0,
    "purity": "925",
    "fineness": 0.925,
    "quotedFineness": 0.925,
    "rate": 496941,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "FIXED",
      "value": 221714
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 11.43
    },
    "expected": {
      "net": 23.189,
      "fine": 21.45,
      "metalValue": 11523565,
      "wastageWeight": 2.651,
      "wastageValue": 1317391,
      "makingCharges": 221714,
      "subtotal": 13062670,
      "discount": 0,
      "taxableValue": 13062670,
      "cgst": 0,
      "sgst": 0,
      "igst": 391880,
      "totalTax": 391880,
      "finalAmount": 13454550
    }
  },
  {
    "gross": 27.211,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 472293,
    "pieces": 12,
    "stoneValue": 2099661,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 270444
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 57.97,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 22783828,
    "expected": {
      "net": 27.211,
      "fine": 15.918,
      "metalValue": 7525691,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 3245328,
      "subtotal": 12870680,
      "discount": 1881317,
      "taxableValue": 10989363,
      "cgst": 0,
      "sgst": 0,
      "igst": 329681,
      "totalTax": 329681,
      "finalAmount": 11319044,
      "grossMargin": -11794465,
      "marginPercentage": -107.33
    }
  },
  {
    "gross": 60.142,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.585,
    "rate": 895419,
    "pieces": 12,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 14426
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 13.45
    },
    "expected": {
      "net": 60.142,
      "fine": 35.183,
      "metalValue": 53852289,
      "wastageWeight": 13.45,
      "wastageValue": 12043386,
      "makingCharges": 867608,
      "subtotal": 66763283,
      "discount": 0,
      "taxableValue": 66763283,
      "cgst": 0,
      "sgst": 0,
      "igst": 2002898,
      "totalTax": 2002898,
      "finalAmount": 68766181
    }
  },
  {
    "gross": 81.826,
    "stone": 55.529,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.999,
    "rate": 115618,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "FIXED",
      "value": 165937
    },
    "discount": {
      "type": "FLAT",
      "value": 55562,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 1740719,
    "expected": {
      "net": 26.297,
      "fine": 24.982,
      "metalValue": 2891277,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 165937,
      "subtotal": 3057214,
      "discount": 55562,
      "taxableValue": 3001652,
      "cgst": 0,
      "sgst": 0,
      "igst": 90050,
      "totalTax": 90050,
      "finalAmount": 3091702,
      "grossMargin": 1260933,
      "marginPercentage": 42.01
    }
  },
  {
    "gross": 83.426,
    "stone": 0.0,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 164436,
    "pieces": 5,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_PIECE",
      "value": 44679
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 76.63,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 19919841,
    "expected": {
      "net": 83.426,
      "fine": 62.57,
      "metalValue": 10298977,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 223395,
      "subtotal": 10522372,
      "discount": 171188,
      "taxableValue": 10351184,
      "cgst": 0,
      "sgst": 0,
      "igst": 310536,
      "totalTax": 310536,
      "finalAmount": 10661720,
      "grossMargin": -9568657,
      "marginPercentage": -92.44
    }
  },
  {
    "gross": 10.889,
    "stone": 0.0,
    "purity": "950",
    "fineness": 0.95,
    "quotedFineness": 0.95,
    "rate": 194661,
    "pieces": 12,
    "stoneValue": 3695363,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 174515
    },
    "wastage": {
      "type": "PERCENTAGE",
      "value": 9.21
    },
    "expected": {
      "net": 10.889,
      "fine": 10.345,
      "metalValue": 2119664,
      "wastageWeight": 1.003,
      "wastageValue": 195245,
      "makingCharges": 2094180,
      "subtotal": 8104452,
      "discount": 0,
      "taxableValue": 8104452,
      "cgst": 121567,
      "sgst": 121567,
      "igst": 0,
      "totalTax": 243134,
      "finalAmount": 8347586
    }
  },
  {
    "gross": 121.906,
    "stone": 44.161,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 384964,
    "pieces": 1,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 198070
    },
    "discount": {
      "type": "FLAT",
      "value": 8723733,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 11970061,
    "expected": {
      "net": 77.745,
      "fine": 58.309,
      "metalValue": 22469239,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 15398952,
      "subtotal": 37868191,
      "discount": 8723733,
      "taxableValue": 29144458,
      "cgst": 0,
      "sgst": 0,
      "igst": 874334,
      "totalTax": 874334,
      "finalAmount": 30018792,
      "grossMargin": 17174397,
      "marginPercentage": 58.93
    }
  },
  {
    "gross": 65.417,
    "stone": 0.0,
    "purity": "22K",
    "fineness": 0.916,
    "quotedFineness": 0.999,
    "rate": 335207,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_PIECE",
      "value": 242058
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 31.24,
      "appliesTo": "MAKING_CHARGES"
    },
    "expected": {
      "net": 65.417,
      "fine": 59.922,
      "metalValue": 20106371,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 242058,
      "subtotal": 20348429,
      "discount": 75619,
      "taxableValue": 20272810,
      "cgst": 304092,
      "sgst": 304092,
      "igst": 0,
      "totalTax": 608184,
      "finalAmount": 20880994
    }
  },
  {
    "gross": 94.509,
    "stone": 0.0,
    "purity": "14K",
    "fineness": 0.585,
    "quotedFineness": 0.999,
    "rate": 587414,
    "pieces": 2,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PERCENTAGE",
      "value": 22.89
    },
    "discount": {
      "type": "FLAT",
      "value": 7453707,
      "appliesTo": "TOTAL"
    },
    "cost": 17208051,
    "expected": {
      "net": 94.509,
      "fine": 55.288,
      "metalValue": 32509317,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 7441383,
      "subtotal": 39950700,
      "discount": 7453707,
      "taxableValue": 32496993,
      "cgst": 487455,
      "sgst": 487455,
      "igst": 0,
      "totalTax": 974910,
      "finalAmount": 33471903,
      "grossMargin": 15288942,
      "marginPercentage": 47.05
    }
  },
  {
    "gross": 51.653,
    "stone": 0.0,
    "purity": "925",
    "fineness": 0.925,
    "quotedFineness": 0.925,
    "rate": 872300,
    "pieces": 2,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "PER_GRAM",
      "value": 159187
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 51.63,
      "appliesTo": "MAKING_CHARGES"
    },
    "expected": {
      "net": 51.653,
      "fine": 47.779,
      "metalValue": 45056912,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 8222486,
      "subtotal": 53279398,
      "discount": 4245270,
      "taxableValue": 49034128,
      "cgst": 735512,
      "sgst": 735512,
      "igst": 0,
      "totalTax": 1471024,
      "finalAmount": 50505152
    }
  },
  {
    "gross": 194.735,
    "stone": 182.785,
    "purity": "22K",
    "fineness": 0.916,
    "quotedFineness": 0.999,
    "rate": 524752,
    "pieces": 1,
    "stoneValue": 0,
    "intra": true,
    "making": {
      "type": "FIXED",
      "value": 60505
    },
    "wastage": {
      "type": "NONE"
    },
    "expected": {
      "net": 11.95,
      "fine": 10.946,
      "metalValue": 5749790,
      "wastageWeight": 0.0,
      "wastageValue": 0,
      "makingCharges": 60505,
      "subtotal": 5810295,
      "discount": 0,
      "taxableValue": 5810295,
      "cgst": 87154,
      "sgst": 87154,
      "igst": 0,
      "totalTax": 174308,
      "finalAmount": 5984603
    }
  },
  {
    "gross": 139.91,
    "stone": 9.659,
    "purity": "925",
    "fineness": 0.925,
    "quotedFineness": 0.925,
    "rate": 410150,
    "pieces": 12,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PERCENTAGE",
      "value": 26.3
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 26.901
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 31.46,
      "appliesTo": "MAKING_CHARGES"
    },
    "cost": 71121660,
    "expected": {
      "net": 130.251,
      "fine": 120.482,
      "metalValue": 53422448,
      "wastageWeight": 26.901,
      "wastageValue": 11033445,
      "makingCharges": 14050104,
      "subtotal": 78505997,
      "discount": 4420163,
      "taxableValue": 74085834,
      "cgst": 0,
      "sgst": 0,
      "igst": 2222575,
      "totalTax": 2222575,
      "finalAmount": 76308409,
      "grossMargin": 2964174,
      "marginPercentage": 4.0
    }
  },
  {
    "gross": 148.485,
    "stone": 56.17,
    "purity": "18K",
    "fineness": 0.75,
    "quotedFineness": 0.999,
    "rate": 64138,
    "pieces": 5,
    "stoneValue": 0,
    "intra": false,
    "making": {
      "type": "PER_GRAM",
      "value": 156975
    },
    "wastage": {
      "type": "FIXED_WEIGHT",
      "value": 73.455
    },
    "discount": {
      "type": "PERCENTAGE",
      "value": 57.85,
      "appliesTo": "TOTAL"
    },
    "cost": 39848952,
    "expected": {
      "net": 92.315,
      "fine": 69.236,
      "metalValue": 4445120,
      "wastageWeight": 73.455,
      "wastageValue": 3536980,
      "makingCharges": 14491147,
      "subtotal": 22473247,
      "discount": 13000773,
      "taxableValue": 9472474,
      "cgst": 0,
      "sgst": 0,
      "igst": 284174,
      "totalTax": 284174,
      "finalAmount": 9756648,
      "grossMargin": -30376478,
      "marginPercentage": -320.68
    }
  }
];
